version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - "./:/usr/src/app"
    ports:
      - 443:443
      - 80:80
      - 3000:3000
      - 8080:8080
    environment:
      NODE_ENV: ${NODE_ENV}
    container_name: barnyard-app-client
    command: npm run start
    restart: "on-failure:0"